services:
  backend:
    build: .
    ports:
      - "5010:5050"
    volumes:
      - .:/app
      - /app/node_modules
    
    # You can add your database environment variables here if needed
    env_file:
      - ./.env
